// const BASE_URL = 'https://billwebapp.herokuapp.com/api/auth/user/3/'
// const RESERVA_URL = 'https://billwebapp.herokuapp.com/api/reserva/3/'
// const DESPESA_FIXA_URL = 'https://billwebapp.herokuapp.com/api/despesa/fixa/3/'
// const DESPESA_VAR_URL = 'https://billwebapp.herokuapp.com/api/despesa/variavel/3/'
// const DESPESA_ADD_URL = 'https://billwebapp.herokuapp.com/api/despesa/adicional/3/'
