# Generated by Django 3.0.7 on 2020-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rendaMensal',
            field=models.FloatField(null=True),
        ),
    ]
