# Generated by Django 3.0.7 on 2020-06-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=140)),
                ('data', models.DateField(null=True)),
                ('destino', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('valor', models.FloatField()),
                ('aplicado', models.BooleanField(default=False)),
                ('faltaReservar', models.FloatField(null=True)),
                ('totalPrevisto', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=140)),
                ('data', models.DateField(null=True)),
                ('origem', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('valor', models.FloatField()),
                ('recebido', models.BooleanField(default=False)),
                ('faltaReceber', models.FloatField(null=True)),
                ('totalPrevisto', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DespesaVariavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=140)),
                ('data', models.DateField(null=True)),
                ('destino', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('valor', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('totalPago', models.FloatField(null=True)),
                ('faltaPagar', models.FloatField(null=True)),
                ('totalPrevisto', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=140)),
                ('data', models.DateField(null=True)),
                ('destino', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('valor', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('totalPago', models.FloatField(null=True)),
                ('faltaPagar', models.FloatField(null=True)),
                ('totalPrevisto', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DespesaAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=140)),
                ('data', models.DateField(null=True)),
                ('destino', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('valor', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('totalPago', models.FloatField(null=True)),
                ('faltaPagar', models.FloatField(null=True)),
                ('totalPrevisto', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
